# Config file for Air (Live Reload Tool)

# General settings
root = "."         # Project root directory
tmp_dir = "tmp"    # Temporary directory for building
build_delay = 1000 # Delay (in ms) before building after file changes

# Build settings
[build]
cmd = "go build -o ./tmp/main ."                        # Build command
bin = "tmp/main"                                        # Path to the built binary
full_bin = "tmp/main"                                   # Path for the full binary (useful for scripts)
log = "build.log"                                       # File to write build logs (optional)
include_ext = ["go", "tpl", "tmpl", "html"]             # File extensions to watch
exclude_dir = ["vendor", "node_modules", ".git", "tmp"] # Directories to ignore

# Log settings
[log]
level = "debug" # Log level: debug, info, warn, error, fatal
color = true    # Enable colored output

# Miscellaneous settings
[sh]
before = "echo 'Running pre-build tasks...'" # Command to run before build
after = "echo 'Build finished.'"             # Command to run after build

# Development environment variables
[env]
GOPATH = "/path/to/your/gopath"
DB_USER = "user"
DB_PASSWORD = "password"
